# Generated by Django 5.2.7 on 2025-11-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=201, verbose_name='مدت زمان اشتراک')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت اشتراک')),
                ('otion1', models.TextField(blank=True, null=True, verbose_name='توضیحات اشتراک 1')),
                ('otion2', models.TextField(blank=True, null=True, verbose_name='توضیحات اشتراک 2')),
                ('otion3', models.TextField(blank=True, null=True, verbose_name='توضیحات اشتراک 3')),
                ('otion4', models.TextField(blank=True, null=True, verbose_name='توضیحات اشتراک 4')),
                ('otion5', models.TextField(blank=True, null=True, verbose_name='توضیحات اشتراک 5')),
                ('otion6', models.TextField(blank=True, null=True, verbose_name='توضیحات اشتراک 6')),
                ('otion7', models.TextField(blank=True, null=True, verbose_name='توضیحات اشتراک 7')),
            ],
        ),
    ]
