# Generated by Django 5.2.7 on 2025-11-03 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=201, verbose_name='نام دسته بندی')),
                ('descriptions', models.TextField(verbose_name='توضیحات دسته یندی')),
                ('image', models.ImageField(upload_to='cateimage/')),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=201, verbose_name='نام')),
                ('decriptions', models.TextField(verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('coming soon', 'به زودی'), ('not finished', 'درحال ساخت'), ('finished', 'اتمام ساخت')], max_length=201, verbose_name='وضعیت فیلم')),
                ('ep_number', models.PositiveIntegerField(default=1, verbose_name='تعداد قسمت')),
                ('season_number', models.PositiveIntegerField(default=1, verbose_name='تعداد فصل')),
                ('country', models.CharField(max_length=201, verbose_name='کشور سازنده')),
                ('pictrue', models.ImageField(upload_to='movie_pictrues/', verbose_name='عکس فیلم')),
                ('movie_or_not', models.CharField(choices=[('سنمایی', 'Mo'), ('سریال', 'Se')], max_length=201, verbose_name='سریال یا سینمایی')),
                ('imdb_rate', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='نمره ی ای ام دی بی')),
                ('autor', models.CharField(max_length=201, verbose_name='نویسنده')),
                ('director', models.CharField(max_length=201, verbose_name='کاگردان')),
                ('created_at', models.PositiveIntegerField(default=2001, verbose_name='سال ساخت')),
                ('like_counts', models.PositiveIntegerField(default=0, verbose_name='تعداد لایک')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.category', verbose_name='ژانر')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.movies', verbose_name='فیلم')),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
