# Generated by Django 5.1.3 on 2025-11-11 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='like_counts',
        ),
        migrations.AddField(
            model_name='movies',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='movie_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
