# Generated by Django 5.1.3 on 2025-11-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_movies_like_counts_movies_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='descriptions',
            field=models.TextField(verbose_name='توضیحات دسته بندی'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=201, verbose_name='کارگردان'),
        ),
    ]
