# Generated by Django 5.1.3 on 2025-11-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_category_descriptions_alter_movies_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='decriptions',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_or_not',
            field=models.CharField(choices=[('Mo', 'سینمایی'), ('Se', 'سریال')], max_length=201, verbose_name='سریال یا سینمایی'),
        ),
    ]
